linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Memory optimization - will address post-v1.0.0
  gocyclo:
    min-complexity: 20  # Increased for v1.0.0, will refactor post-release
  dupl:
    threshold: 150  # Increased to reduce false positives in command builders
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 150  # Slightly increased for readability
  goimports:
    local-prefixes: github.com/moffa90/go-cyacd
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - appendCombine  # Minor optimization - will address post-v1.0.0
  funlen:
    lines: 100
    statements: 50
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam  # Disabled for v1.0.0 - reports false positives on future-proofed APIs
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - dupl
        - gosec
    - linters:
        - lll
      source: "^//go:generate "

  exclude-dirs:
    - vendor

  exclude-files:
    - ".*\\.pb\\.go$"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
