version: 2

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Memory optimization - will address post-v1.0.0
  gocyclo:
    min-complexity: 20  # Increased for v1.0.0, will refactor post-release
  dupl:
    threshold: 150  # Increased to reduce false positives in command builders
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  # Settings for disabled linters (funlen, lll, gocritic, gosec, revive) removed

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck # Enabled by default
    # - funlen  # Disabled for v1.0.0 - many long test functions
    - gochecknoinits
    - goconst
    # - gocritic  # Disabled for v1.0.0 - minor style issues
    - gocyclo
    # gofmt and goimports are formatters in v2+, not linters
    # - revive  # Disabled for v1.0.0 - config issues with stuttering check
    - goprintffuncname
    # - gosec  # Disabled for v1.0.0 - many false positives on int conversions
    - govet # Enabled by default
    - ineffassign # Enabled by default
    # - lll  # Disabled for v1.0.0 - some long error messages
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck # Enabled by default (includes gosimple and stylecheck)
    # gosimple, stylecheck are now part of staticcheck in v2+
    # typecheck runs automatically in v2+, not a standalone linter
    # unconvert not available in v2+
    # - unparam  # Disabled for v1.0.0 - reports false positives on future-proofed APIs
    - unused # Enabled by default

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - dupl
        - gosec
    - linters:
        - lll
      source: "^//go:generate "

  exclude-dirs:
    - vendor

  exclude-files:
    - ".*\\.pb\\.go$"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
